import "app/global/ui-kit.scss";
import type { Metadata } from "next";
import { AuthProvider } from "app/shared/context/AuthProvider";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <StoreProvider>
          <body data-mode='light'>
            <div id='themeBody' data-mode='light'>
              {children}
            </div>
          </body>
        </StoreProvider>
      </html>
    </AuthProvider>
  );
}
